spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.110.130:3306/gulimall_oms?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: gulimail-order

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 9000